Add 2 Chains
ping-pub/ping.pub pull request #9
Opened 2023-10-07 00:18 UTC by nodeiistt

2023-10-07 06:47 UTC, liangping requested changes

2023-10-07 06:47 UTC, liangping commented on chains/mainnet/realio.json
> +        "base": "ario,arst",
Don't support "," for seperator of two base denoms, add two assets if you need

2023-10-07 06:47 UTC, liangping commented on chains/mainnet/sge.json
> +    "rpc": ["https://rpc.cosmos.directory/sge"],
Is it possible to add more endpoints?

2023-10-10 21:49 UTC, nodeiistt commented
done

2023-10-19 01:56 UTC, liangping requested changes

2023-10-23 21:18 UTC, nodeiistt commented on chains/mainnet/realio.json
> +    "rpc": ["https://rpc.cosmos.directory/realio"],
> please add more endpoint here. and please submit prettify the json.

done!

2023-10-24 01:05 UTC, liangping approved these changes

2023-10-24 01:05 UTC, merged